theme: "auto"
server:
  address: "tcp://:9091"
  endpoints:
    authz:
      forward-auth:
        implementation: ForwardAuth

authentication_backend:
  file:
    path: /config/users_database.yml

totp:
  issuer: auth.example.ru
  period: 30

access_control:
  default_policy: deny
  rules:
    - domain: ["auth.example.ru"] # адрес Authelia
      policy: bypass
    - domain: ["1c.example.ru"] # адрес веб-сервера 1С или reverse proxy
      policy: one_factor

session:
  name: authelia_session
  expiration: 3600
  inactivity: 300
  domain: example.ru

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: "/config/notification.txt"

identity_providers:
  oidc:
    jwks:
      - key_id: 'main'
        algorithm: 'RS256'
        use: 'sig'
        key: {{ secret "/secrets/rsa.2048.key" | mindent 10 "|" | msquote }}

    enable_client_debug_messages: true

    cors:
      endpoints:
        - authorization
        - token
        - userinfo
      allowed_origins:
        - https://1c.example.ru # адрес веб-сервера 1С или reverse proxy
        - https://auth.example.ru # адрес Authelia
      allowed_origins_from_client_redirect_uris: true

    claims_policies:
      id_token_with_email:
        id_token:
          - email
          - email_verified
          - preferred_username
          - name

    clients:
      - client_id: 1c_smb_demo1 # заменить на свой ID
        public: true
        require_pkce: true
        token_endpoint_auth_method: none
        authorization_policy: 'one_factor'
        redirect_uris:
          - 'https://1c.example.ru/smb_demo1/authform.html' # заменить хост и имя базы
        scopes:
          - openid
          - profile
          - email
        response_types:
          - 'code'
        response_modes:
          - 'fragment'
          - 'query'
          - 'form_post'
        grant_types:
          - 'authorization_code'
          - 'refresh_token'
        claims_policy: id_token_with_email

        # Алгоритмы подписи
        id_token_signed_response_alg: 'RS256'
        userinfo_signed_response_alg: 'none'
