theme: "auto"
server:
  address: "tcp://:9091"
  endpoints:
    authz:
      forward-auth:
        implementation: ForwardAuth

authentication_backend:
  file:
    path: /config/users_database.yml

totp:
  issuer: auth.example.ru
  period: 30

access_control:
  default_policy: deny
  rules:
    - domain: ["auth.example.ru"] # адрес Authelia
      policy: bypass
    - domain: ["1c.example.ru"] # адрес веб-сервера 1С или reverse proxy
      policy: one_factor

session:
  name: authelia_session
  expiration: 3600
  inactivity: 300
  domain: example.ru

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: "/config/notification.txt"

identity_providers:
  oidc:
    jwks:
      - key_id: 'main'
        algorithm: 'RS256'
        use: 'sig'
        key: {{ secret "/secrets/rsa.2048.key" | mindent 10 "|" | msquote }}

    enable_client_debug_messages: true

    cors:
      endpoints:
        - authorization
        - token
        - userinfo
      allowed_origins:
        - https://1c.example.ru # адрес веб-сервера 1С или reverse proxy
        - https://auth.example.ru # адрес Authelia
      allowed_origins_from_client_redirect_uris: true

    claims_policies:
      id_token_with_email:
        id_token:
          - email
          - email_verified
          - preferred_username
          - name

    clients:
      - client_id: 1c_smb_demo1
        client_secret: '$pbkdf2-sha512$310000$FaIxSENlaIapeRsTzkJ5KQ$HD/SaV.pdE2udh9fSN5YiG8z5PCE5v9F7MxY8D4hwjmRVRpEHJZur5.feRFu.NMgsv8BfXSxplL/9pNF4hAoeA'
        public: false
        authorization_policy: 'one_factor'
        consent_mode: 'implicit'
        redirect_uris:
          - 'https://1c.example.ru/smb_demo1/authform.html' # заменить хост и имя базы
          - 'https://jwt.ms' # Для отладки содержимого jwt
        scopes:
          - openid
          - profile
          - email
        response_types:
          - 'id_token token'
        response_modes:
          - 'fragment'
        grant_types:
          - 'implicit'
        claims_policy: id_token_with_email

        # Алгоритмы подписи
        id_token_signed_response_alg: 'RS256'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'

